---
server:
  port: 8181

spring:
  config:
    activate:
      on-profile: dev
---
server:
  port: 8182

spring:
  config:
    activate:
      on-profile: qa
---
spring:
  profiles:
    active: dev

name: yunpeng
owner:
  name: Randren
  age: 27

studyDate:
  - 2024.04
  - 2024.05